# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 04:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0008_auto_20200401_0651'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='def_photo',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=b''),
        ),
        migrations.AlterField(
            model_name='post',
            name='photo',
            field=models.ImageField(upload_to=b''),
        ),
    ]
