# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 04:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0009_auto_20200402_0420'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='def_photo',
        ),
    ]
