# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 05:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0012_auto_20200402_0532'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='def_picture',
            field=models.ImageField(blank=True, upload_to=b''),
        ),
    ]
