# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0013_auto_20200402_0543'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='def_picture',
            field=models.ImageField(blank=True, default='default.jpg', upload_to=b''),
        ),
    ]
