# -*- coding: utf-8 -*-
# Generated by Django 1.11.29 on 2020-04-02 12:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('timeline', '0014_auto_20200402_0732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='user_name',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
